import Head from 'next/head'
import ArticleCard from '../components/enviroment/ArticleCard'
import styles from '../styles/Home.module.css'
import Presentation from '../components/enviroment/Presentation'
import Grid from '../components/enviroment/Grid'
export default function Home() {
  return (
    <div>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Presentation 
      header="CREATE AND SHARE YOUR PHOTO STORIES." 
      text="Photosnap is a platform for photographers and visual storytellers. We make it easy to share photos, tell stories and connect with others." 
      
      />

      <Presentation 
      header="Beautiful stories everytime." 
      text="We provide design templates to ensure your stories look terrific. Easily add photos, text, embed maps and media from other networks. Then share your story with everyone." 
      img='/images/beautiful-stories.jpg'
      reverse={true}
      isBlack={false}
      />
      <Presentation 
      header="Designed for everyone." 
      text="Photosnap can help you create stories that resonate with your audience. Our tool is designed for photographers of all levels, brands, businesses you name it." 
      img='/images/designed-for-everyone.jpg'
      />
      <Grid>
        <ArticleCard />
        <ArticleCard />
        <ArticleCard />
        <ArticleCard />
      </Grid>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        
      </main>
    </div>
  )
}
